import './globals.css';
import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({children}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body>
    <Link href="/">主页</Link>
    &nbsp;
    <Link href="/user">用户</Link>
    &nbsp;
    <Link href="/user/list">用户列表</Link>
    {children}
    </body>
    </html>
  );
}
