on: [ push ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 部署
    steps:
      - name: 拉取代码
        id: checkout
        uses: actions/checkout@v4
      - name: 打包
        run: |
          npm ci
          npm run build
          touch docs/.nojekyll
      - name: 部署到gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
